. "$HOME/.local/bin/env"
export PATH=~/.npm-global/bin:$PATH
export PATH="/opt/homebrew/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/Users/ibuddhar/.local/share/solana/install/active_release/bin:$PATH"

alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias la="ls -a"
